Uniswap price feed backend
defi-helper/defihelper-backend pull request #294
Opened 2022-08-23 14:22 UTC by Lukentui

2022-08-24 07:49 UTC, Bashka commented on src/api/schema/token/index.ts
> +          route: { type: GraphQLNonNull(GraphQLList(GraphQLNonNull(GraphQLString))) },
нет поля exchange с адресом роутера юни для обращения

2022-08-24 07:49 UTC, Bashka commented on src/models/Token/Entity.ts
> +    route: string[];
тут тоже должен быть exchange, яб переименовал route в path, оно так называется у юни

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +  switch (token.network) {
убери switch, перепиши на

```
const routerAddress = {
  '1': '0x...',
  ...
}[token.network]
```

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +  const abi = [
это в файл по адресу src/services/Blockchain/abi/ethereum/uniswapV2Router.json

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +
добавь проверку на token.blockchain === 'ethereum', эта штука не умеет работать в других бч

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +  const provider = networkContainer.provider();
нет смысла в этой константе, она используется у тебя в следующем аргументе, там и вызывай запрос провайдера

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +    return [token.address, stablecoin];
```
const possibleRoutes = networkContainer.stablecoins.flatMap((stablecoin) => {
    return [
      [token.address, stablecoin],
      [token.address, networkContainer.wrappedNativeTokenAddress, stablecoin]
    ];
  });
  ```

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +          new BigNumber(`1e${token.decimals}`).toString(10),
toFixed(0), в методы бч нельзя передавать числа с долями

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +        await uniV2RouterContract.getAmountsOut(
а чо не

```
return uniRouter.getAmounts(...)
  .then(() => possibleRoute)
  .catch(() => null);
```

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealer.ts
> +
Добавь проверку на priceFeed === null, чтоб таска не меняла прайсфид для токена, у которого он уже указан

2022-08-24 07:49 UTC, Bashka commented on src/queue/contract/uniswapRouteRevealerBroker.ts
> +  id: string;
что это?

2022-08-24 07:49 UTC, Bashka commented on src/queue/index.ts
> +export * as tokenResolveUniswapRoute from './contract/uniswapRouteRevealer';
почему в contract а не в token?

2022-08-24 07:49 UTC, Bashka commented on src/services/Blockchain/Ethereum.ts
> +import { abi as uniswapRouterABI } from '@defihelper/networks/abi/Budget.json'; // todo fixme
шо це?

2022-08-24 07:49 UTC, Bashka commented on src/services/Blockchain/Ethereum.ts
> +    wrappedNativeTokenAddress,
засунь это в nativeTokenDetails, можно ключ wrapperAddress

2022-08-24 07:49 UTC, Bashka commented on src/services/Blockchain/Ethereum.ts
> +      wrappedNativeTokenAddress: '',
если обертка может не быть, то string | null, на уровне резолвера проверка на наличие обертки и пропуск роута с нативом если null

2022-08-24 07:49 UTC, Bashka commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [],
если стейблов в сети может не быть, то проверка на уровне резолвера и пропуск сети

2022-08-24 13:25 UTC, Lukentui commented on src/queue/contract/uniswapRouteRevealer.ts
> +  const provider = networkContainer.provider();
не правда, там ниже в 2х местах используется эта константа еще

2022-08-24 13:29 UTC, Lukentui commented on src/queue/contract/uniswapRouteRevealerBroker.ts
> +  id: string;
не понимаю

2022-08-24 13:31 UTC, Lukentui commented on src/services/Blockchain/Ethereum.ts
> +import { abi as uniswapRouterABI } from '@defihelper/networks/abi/Budget.json'; // todo fixme
ждем влада

2022-08-24 13:31 UTC, Lukentui commented on src/queue/contract/uniswapRouteRevealer.ts
> +  const abi = [
ждем влада

2022-08-24 13:54 UTC, Bashka commented on src/api/schema/token/index.ts
> +          route: { type: GraphQLNonNull(GraphQLList(GraphQLNonNull(GraphQLString))) },
нет полей для заполнения интерфейса прайсфида UniswapRouterV2

2022-08-24 13:54 UTC, Bashka commented on src/queue/token/uniswapRouteRevealer.ts
> +    throw new Error(`Could not find contract with id ${id}`);
при чем здесь контракт?

2022-08-24 13:54 UTC, Bashka commented on src/queue/token/uniswapRouteRevealer.ts
> +  if (!token) {
сюда попадет токен с blockchain = waves что не правда, токен будет найден, но в другом бч

2022-08-24 13:54 UTC, Bashka commented on src/queue/token/uniswapRouteRevealer.ts
> +  const abi = [
в файл

2022-08-24 13:54 UTC, Bashka commented on src/queue/token/uniswapRouteRevealer.ts
> +  if (!networkContainer.nativeTokenDetails.wrapped) {
```
const wrappedNative = networkContainer.nativeTokenDetails.wrapped;
if (!wrappedNative) throw ...

...
```
и внизу убери as string

2022-08-24 14:00 UTC, Lukentui commented on src/queue/token/uniswapRouteRevealer.ts
> +  if (!token) {
на 26 строке проверка бч

2022-08-29 06:34 UTC, mastyf commented on src/queue/token/uniswapRouteRevealer.ts
> +  const routerByNetwork = {
Скорее всего, так работать не будет. У тебя внутри одной сети может быть несколько бирж и роутеров. То есть, у тебя в BSC есть Pancakeswap и biswap, а ты всегда ходишь на роутер кейка для резолва цены и, скорее всего, там будут цены хуже или не будет вообще. Скорее всего, надо привязывать протокол к бирже или определять по LP токену.

2022-08-29 06:34 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
Список стейблов у нас есть в БД, в каждой сети у них свои адреса

2022-08-29 06:35 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +        wrapped: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
тоже непонятно к какой сети это относится

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:36 UTC, mastyf commented on src/services/Blockchain/Ethereum.ts
> +      stablecoins: [
А почему не из БД? Список стейблов может меняться.

2022-08-29 06:37 UTC, mastyf requested changes
надо поправить

2022-08-30 07:43 UTC, Bashka commented on src/queue/token/uniswapRouteRevealer.ts
> +  const representativeTokenErc20Contract = blockchainContainer.contract(
слишком длинное и сложное имя, token = erc20, нет смысла повторяться, можно назвать просто exitToken или outputToken или убрать вообще константу

```
  const outputDecimals = await blockchainContainer.contract(...).decimals();

2022-08-30 07:43 UTC, Bashka commented on src/queue/token/uniswapRouteRevealerBroker.ts
> +        .distinctOn(`${tokenTableName}.network`)
зачем здесь distinct on?

2022-10-18 13:11 UTC, merged